//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int cntid { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> City { get; set; }
        public string Statename { get; set; }
        public string DisttName { get; set; }
        public string Cityname { get; set; }
        public string ProjCode { get; set; }
        public string CompType { get; set; }
        public string ProjName { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<decimal> ProjCost { get; set; }
        public Nullable<int> Houses { get; set; }
        public Nullable<int> Grounded { get; set; }
        public Nullable<int> Completed { get; set; }
    }
}
