//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification_City_Mapping
    {
        public long CityClassId { get; set; }
        public string StateCode { get; set; }
        public string DistrictCode { get; set; }
        public string CityCode { get; set; }
        public string DescriptionCode { get; set; }
        public string Selected { get; set; }
    }
}
