//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLSS_MAster__Oct_17
    {
        public long SrNo { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public Nullable<double> Loan_EWS_LIG { get; set; }
        public Nullable<double> Subsidy_EWS_LIG { get; set; }
        public Nullable<double> No_Beneficiary_EWS_LIG { get; set; }
        public Nullable<double> Loan_MIG { get; set; }
        public Nullable<double> Subsidy_MIG { get; set; }
        public Nullable<double> No_Beneficiary_MIG { get; set; }
        public Nullable<double> Loan_TOTAL { get; set; }
        public Nullable<double> Subsidy_Total { get; set; }
        public Nullable<double> NoBeneficiary_Total { get; set; }
        public string Division { get; set; }
        public Nullable<double> Bene2014_15 { get; set; }
        public Nullable<double> Bene2015_16 { get; set; }
        public Nullable<double> Bene2016_17 { get; set; }
        public Nullable<double> Bene2017_18 { get; set; }
        public Nullable<double> Bene2018_19 { get; set; }
        public Nullable<double> Bene2019_20 { get; set; }
        public Nullable<double> Bene2020_21 { get; set; }
        public Nullable<double> Bene2021_22 { get; set; }
        public Nullable<double> Subsidy2014_15 { get; set; }
        public Nullable<double> Subsidy2015_16 { get; set; }
        public Nullable<double> Subsidy2016_17 { get; set; }
        public Nullable<double> Subsidy2017_18 { get; set; }
        public Nullable<double> Subsidy2018_19 { get; set; }
        public Nullable<double> Subsidy2019_20 { get; set; }
        public Nullable<double> Subsidy20_21 { get; set; }
        public Nullable<double> Subsidy21_22 { get; set; }
    }
}
