//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLSS_MASTER_9_Aug_2019
    {
        public long SrNo { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public Nullable<double> Loan_EWS_LIG { get; set; }
        public Nullable<double> Subsidy_EWS_LIG { get; set; }
        public Nullable<double> No_Beneficiary_EWS_LIG { get; set; }
        public Nullable<double> Loan_MIG { get; set; }
        public Nullable<double> Subsidy_MIG { get; set; }
        public Nullable<double> No_Beneficiary_MIG { get; set; }
        public Nullable<double> Loan_TOTAL { get; set; }
        public Nullable<double> Subsidy_Total { get; set; }
        public Nullable<double> NoBeneficiary_Total { get; set; }
        public string Division { get; set; }
    }
}
