//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clss_Mainmaster_9Aug2019
    {
        public long SrNo { get; set; }
        public string state_Name { get; set; }
        public Nullable<double> State_Code { get; set; }
        public string District_Name { get; set; }
        public Nullable<double> Dcode { get; set; }
        public string City_Name { get; set; }
        public Nullable<double> CityCode { get; set; }
        public Nullable<double> EWS_Bene { get; set; }
        public Nullable<double> EWS_Loan_Amt { get; set; }
        public Nullable<double> EWS_Subsidy { get; set; }
        public Nullable<double> LIG_Bene { get; set; }
        public Nullable<double> LIG_Loan_Amt { get; set; }
        public Nullable<double> LIG_Subsidy { get; set; }
        public Nullable<double> MIG1_Bene { get; set; }
        public Nullable<double> MIG1_Loan_Amt { get; set; }
        public Nullable<double> MIG1_SubsidyAmt { get; set; }
        public Nullable<double> MIG2_Bene { get; set; }
        public Nullable<double> MIG2_Loan_Am { get; set; }
        public Nullable<double> MIG2_SubsidyAmt { get; set; }
        public Nullable<double> Total_LoanAmt { get; set; }
        public Nullable<double> Total_SubsidyAmt { get; set; }
        public Nullable<double> Total_Beneficiaries { get; set; }
        public Nullable<int> Cid { get; set; }
        public string Division { get; set; }
    }
}
