//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmaster
    {
        public int Cid { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string Cname { get; set; }
        public string SchemeComponentName { get; set; }
        public string SchemeShortName { get; set; }
        public Nullable<bool> sFlag { get; set; }
    }
}
