//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combined_States
    {
        public long SrNo { get; set; }
        public string Name_of_the_State__UT { get; set; }
        public Nullable<double> Project_Proposal_Considered { get; set; }
        public Nullable<double> Financial_Progress__Rs_in_Crore_ { get; set; }
        public Nullable<double> CAApproved { get; set; }
        public Nullable<double> CAReleased { get; set; }
        public Nullable<double> HousesApproved { get; set; }
        public Nullable<double> Grounded { get; set; }
        public Nullable<double> Completed { get; set; }
        public Nullable<double> Occupied { get; set; }
    }
}
