//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandCityWise_
    {
        public long SrNo { get; set; }
        public string State_Name { get; set; }
        public Nullable<double> State_Code { get; set; }
        public string District_Name { get; set; }
        public Nullable<double> District_Code { get; set; }
        public string CITY_Name { get; set; }
        public Nullable<double> City_Code { get; set; }
        public Nullable<double> ISSR { get; set; }
        public Nullable<double> AHP { get; set; }
        public Nullable<double> BLC { get; set; }
        public Nullable<double> CLSS { get; set; }
        public Nullable<double> demand { get; set; }
        public Nullable<int> Cid { get; set; }
    }
}
