//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distt_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distt_Master()
        {
            this.Users_Register = new HashSet<Users_Register>();
        }
    
        public long DisttId { get; set; }
        public string District { get; set; }
        public string Distt { get; set; }
        public string StateCode { get; set; }
        public string Dcode { get; set; }
        public string sunDisttCode { get; set; }
        public string BackwardDistrict { get; set; }
        public string Minority { get; set; }
        public string ActiveFlag { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedOn { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Register> Users_Register { get; set; }
    }
}
