//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distt_Master_old
    {
        public int DisttId { get; set; }
        public string District { get; set; }
        public Nullable<double> Dcode { get; set; }
        public Nullable<double> sunDisttCode { get; set; }
        public Nullable<double> StateCode { get; set; }
    }
}
