//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string PinCode { get; set; }
        public string Gender { get; set; }
        public string FileUpload { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Password { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
