//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public long SrNo { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string sImage { get; set; }
        public string ImagePath { get; set; }
    }
}
