//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalCity
    {
        public long CityId { get; set; }
        public string City { get; set; }
        public string Dcode { get; set; }
        public string sunDisttCode { get; set; }
        public string CityCode { get; set; }
    }
}
