//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public long SrNo { get; set; }
        public string SrareName { get; set; }
        public string StateCode { get; set; }
        public Nullable<double> Demand { get; set; }
        public Nullable<double> HousesSanctioned { get; set; }
        public Nullable<double> CentralShare { get; set; }
        public Nullable<double> StateShare { get; set; }
        public Nullable<double> ULBShare { get; set; }
        public Nullable<double> BeneficiaryShare { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> Grounded { get; set; }
        public Nullable<double> Completed { get; set; }
        public Nullable<double> Occupied { get; set; }
        public Nullable<double> CAApproved { get; set; }
        public Nullable<double> CASanctforRelease { get; set; }
        public Nullable<double> CAssitReleased { get; set; }
        public Nullable<double> PendingforRelease { get; set; }
    }
}
