//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment_Details
    {
        public long InvestmentId { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<decimal> CentralShare { get; set; }
        public Nullable<decimal> StateShare { get; set; }
        public Nullable<decimal> ULBShare { get; set; }
        public Nullable<decimal> Beneficiary { get; set; }
    }
}
