//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JnNURM_Copy_1
    {
        public long id { get; set; }
        public Nullable<double> SrNo { get; set; }
        public string Project_Code { get; set; }
        public string State { get; set; }
        public string Scheme { get; set; }
        public string Distt { get; set; }
        public string CityTown { get; set; }
        public string State_Code { get; set; }
        public string DisttCode { get; set; }
        public string SubDisttCode { get; set; }
        public string TownCode { get; set; }
        public string Project_Title { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public string Cancelled_Date { get; set; }
        public Nullable<double> O_ProjectCost_ { get; set; }
        public Nullable<double> O_CentrallShare { get; set; }
        public Nullable<double> O_DwellingUnit { get; set; }
        public Nullable<double> ProjCost { get; set; }
        public Nullable<double> Central_Share { get; set; }
        public Nullable<double> DwellingUnit { get; set; }
        public Nullable<double> Central_Share_Released__Projects_ { get; set; }
        public Nullable<double> Central_Share_Adjusted { get; set; }
        public Nullable<double> Excess_ACA_Released { get; set; }
        public Nullable<double> Central_Share_Refunded_by_State_Govt_ { get; set; }
        public Nullable<double> UC_Received { get; set; }
        public Nullable<double> Pending_UC { get; set; }
        public Nullable<double> Under_Progress { get; set; }
        public Nullable<double> Completed { get; set; }
        public Nullable<double> Allotted { get; set; }
        public Nullable<double> Occupied { get; set; }
        public Nullable<double> Un_Occupied { get; set; }
        public Nullable<double> Non_Starter { get; set; }
        public Nullable<double> Grounded { get; set; }
        public Nullable<double> Completed1 { get; set; }
        public Nullable<double> Occupied1 { get; set; }
    }
}
