//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Cities_Included
    {
        public int SrNo { get; set; }
        public string StateCode { get; set; }
        public string Name_of_the_State__UT { get; set; }
        public Nullable<double> Cities_included_in_mission { get; set; }
    }
}
