//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physical_Progress_Report
    {
        public long PhysicalProgressId { get; set; }
        public string Codes { get; set; }
        public string Dcode { get; set; }
        public string CityCode { get; set; }
        public string Scheme { get; set; }
        public string ProjectCode { get; set; }
        public string CentralAssistance { get; set; }
        public string TotalSanction { get; set; }
        public string GroundLevel { get; set; }
        public string Pinth { get; set; }
        public string LinterLevel { get; set; }
        public string RoofLevel { get; set; }
        public string SuperStructure { get; set; }
        public string FinishingStage { get; set; }
        public Nullable<decimal> TotalProgressHouse { get; set; }
        public Nullable<decimal> ConstructionCompleted { get; set; }
        public string NonStarterHouse { get; set; }
        public string PowerSupply { get; set; }
        public string WaterSupply { get; set; }
        public string DrainageSupply { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> TotalHouseOccupiedBeneficiary { get; set; }
    }
}
