//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physical_Dashboard_Back
    {
        public long SrNo { get; set; }
        public Nullable<double> State1 { get; set; }
        public string StateCode { get; set; }
        public Nullable<double> Demand { get; set; }
        public Nullable<double> Houses_Sanctioned { get; set; }
        public Nullable<double> CentralShare { get; set; }
        public Nullable<double> StateShare { get; set; }
        public Nullable<double> ULBShare { get; set; }
        public Nullable<double> BeneficiaryShare { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> Grounded { get; set; }
        public Nullable<double> Completed { get; set; }
        public Nullable<double> Occupied { get; set; }
        public Nullable<double> CAApproved { get; set; }
        public Nullable<double> CASanctionedforRelease { get; set; }
        public Nullable<double> CAReleased { get; set; }
        public Nullable<double> PendingforRelease { get; set; }
        public Nullable<double> IIIQ_15_16 { get; set; }
        public Nullable<double> IV_Q_15_16 { get; set; }
        public Nullable<double> IQ_16_17 { get; set; }
        public Nullable<double> IIQ_16_17 { get; set; }
        public Nullable<double> IIIQ_16_17 { get; set; }
        public Nullable<double> IV_Q_16_17 { get; set; }
        public Nullable<double> I_Q_17_18 { get; set; }
        public Nullable<double> II_Q_17_18 { get; set; }
        public Nullable<double> III_Q_17_18 { get; set; }
        public Nullable<double> IV_Q_17_18 { get; set; }
        public Nullable<double> I_Q_18_19 { get; set; }
        public Nullable<double> II_Q_18_19 { get; set; }
        public Nullable<double> III_Q_18_19 { get; set; }
        public Nullable<double> IV_Q_18_19 { get; set; }
        public Nullable<double> I_Q_19_20 { get; set; }
        public Nullable<double> SRNo1 { get; set; }
        public Nullable<double> State2 { get; set; }
        public Nullable<double> CumSanctioned { get; set; }
        public Nullable<double> CASanctioned_15_16 { get; set; }
        public Nullable<double> CASanctioned_16_17 { get; set; }
        public Nullable<double> CASanctioned_17_18 { get; set; }
        public Nullable<double> CASanctioned_18_19 { get; set; }
        public Nullable<double> CASanctioned_19_20 { get; set; }
        public Nullable<double> CumuCAReleased { get; set; }
        public Nullable<double> CumuCA_Released_15_16 { get; set; }
        public Nullable<double> CumuCA_Released_16_17 { get; set; }
        public Nullable<double> CumuCA_Released_17_18 { get; set; }
        public Nullable<double> CumuCA_Released_18_19 { get; set; }
        public Nullable<double> CumuCA_Released_19_20 { get; set; }
        public string k { get; set; }
        public string ll { get; set; }
        public Nullable<double> HS_Cum_20_8_18 { get; set; }
        public Nullable<double> HS_15_16 { get; set; }
        public Nullable<double> HS_16_17 { get; set; }
        public Nullable<double> HS_17_18 { get; set; }
        public Nullable<double> HS_18_19 { get; set; }
        public Nullable<double> HS_19_20 { get; set; }
        public Nullable<double> HC_20_08_18 { get; set; }
        public Nullable<double> HC_14_15 { get; set; }
        public Nullable<double> HC_15_16 { get; set; }
        public Nullable<double> HC_16_17 { get; set; }
        public Nullable<double> HC_17_18 { get; set; }
        public Nullable<double> HC_18_19 { get; set; }
        public Nullable<double> HC_19_20 { get; set; }
        public Nullable<double> HO_Cum { get; set; }
        public Nullable<double> HO_14_15 { get; set; }
        public Nullable<double> HO_15_16 { get; set; }
        public Nullable<double> HO_16_17 { get; set; }
        public Nullable<double> HO_17_18 { get; set; }
        public Nullable<double> HO_18_19 { get; set; }
        public Nullable<double> HO_19_20 { get; set; }
        public Nullable<double> F63 { get; set; }
        public Nullable<double> Expenditure { get; set; }
        public string Division { get; set; }
    }
}
