//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMAY_PROJECTS_Copy___1
    {
        public long StNo { get; set; }
        public Nullable<double> S__No_ { get; set; }
        public string Project_Code { get; set; }
        public string Annexure_ID__PMAY_MIS_ { get; set; }
        public string Component_ { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State_Code { get; set; }
        public string Dcode { get; set; }
        public string sunDisttCode { get; set; }
        public string CityCode { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> CSMCDate { get; set; }
        public Nullable<double> CSMCNo_ { get; set; }
        public Nullable<double> F__Year { get; set; }
        public Nullable<double> No_of_Projects { get; set; }
        public Nullable<double> Project__Cost { get; set; }
        public Nullable<double> Central_Assistance_involved { get; set; }
        public Nullable<double> State_Grant { get; set; }
        public Nullable<double> ULB_Share { get; set; }
        public Nullable<double> Beneficiary_Share { get; set; }
        public Nullable<double> Released_through_EBR { get; set; }
        public Nullable<double> First_Installment_Released { get; set; }
        public Nullable<double> Second_Installment_Released { get; set; }
        public Nullable<double> CASanctionedForRel { get; set; }
        public Nullable<double> Central_Assistance_Released { get; set; }
        public Nullable<double> UC__Received { get; set; }
        public Nullable<double> UC__Pending { get; set; }
        public Nullable<double> Houses_involved { get; set; }
        public Nullable<double> Funds_Disbursed_in_Houses { get; set; }
        public Nullable<double> Houses_Grounded { get; set; }
        public Nullable<double> Houses_Under_Progress { get; set; }
        public Nullable<double> Houses_Completed { get; set; }
        public Nullable<double> Houses_Allotted { get; set; }
        public Nullable<double> Houses_Occupied { get; set; }
        public Nullable<double> Houses__yet_to_Grounded { get; set; }
    }
}
