//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMAYU_MainDashboard
    {
        public long RowId { get; set; }
        public string Sanctioned { get; set; }
        public string Grounded { get; set; }
        public string Completed { get; set; }
        public string Occupied { get; set; }
        public string sCommitted { get; set; }
        public string Approved { get; set; }
        public string Released { get; set; }
        public string Utilized { get; set; }
        public string Overall { get; set; }
        public string sPublic { get; set; }
        public string Private { get; set; }
        public string PDaysDirect { get; set; }
        public string PDaysIndirect { get; set; }
        public string PDaysTotal { get; set; }
        public string JobsDirect { get; set; }
        public string JobsIndirect { get; set; }
        public string JobsTotal { get; set; }
        public string sActive { get; set; }
    }
}
