//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMAY_PROJECTS_Fin_July
    {
        public long SrNo { get; set; }
        public string Project_Code { get; set; }
        public string Annexure_ID { get; set; }
        public string Component { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string Dcode { get; set; }
        public string sunDisttCode { get; set; }
        public string CityCode { get; set; }
        public string Project_Name { get; set; }
        public string CSMCDate { get; set; }
        public Nullable<double> CSMCNo { get; set; }
        public string FinYear { get; set; }
        public Nullable<double> NoofProjects { get; set; }
        public Nullable<double> Project_Cost { get; set; }
        public Nullable<double> Central_Assistance_involved { get; set; }
        public Nullable<double> State_Grant { get; set; }
        public Nullable<double> ULBShare { get; set; }
        public Nullable<double> BeneficiaryShare { get; set; }
        public Nullable<double> Released_throug_EBR { get; set; }
        public Nullable<double> CASanctionedForRel { get; set; }
        public Nullable<double> FirstInstallmentReleased { get; set; }
        public Nullable<double> SecondInstallmentReleased { get; set; }
        public Nullable<double> ThirdInstallmentReleased { get; set; }
        public Nullable<double> CentralAssistanceReleased { get; set; }
        public Nullable<double> UC_Received { get; set; }
        public Nullable<double> UC_Pending { get; set; }
        public Nullable<double> Housesinvolved { get; set; }
        public Nullable<double> FundsDisbursed_in_Houses { get; set; }
        public Nullable<double> Houses_Grounded { get; set; }
        public Nullable<double> HousesUnderProgress { get; set; }
        public Nullable<double> Houses_Completed { get; set; }
        public Nullable<double> HousesAllotted { get; set; }
        public Nullable<double> HousesOccupied { get; set; }
        public Nullable<double> Houses_yetto_Grounded { get; set; }
        public Nullable<int> Cid { get; set; }
    }
}
