//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_UC_Order
    {
        public long UCOrderID { get; set; }
        public string State { get; set; }
        public string SanctionNo { get; set; }
        public Nullable<double> UCAmount { get; set; }
        public string UtilizationNo { get; set; }
        public Nullable<System.DateTime> UCDate { get; set; }
        public string UCPDF { get; set; }
    }
}
