//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Release_Order
    {
        public long ReleaseOrderID { get; set; }
        public string State { get; set; }
        public string SanctionNo { get; set; }
        public string Scheme { get; set; }
        public string Component { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> AmountReleased { get; set; }
        public string ReleasePDF { get; set; }
    }
}
