//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_UC_Submission
    {
        public long UCID { get; set; }
        public string Codes { get; set; }
        public string Dcode { get; set; }
        public string CityCode { get; set; }
        public string ProjectCode { get; set; }
        public string SanctionNumber { get; set; }
        public Nullable<long> ReleaseId { get; set; }
        public string Release { get; set; }
        public string Installment { get; set; }
        public string LetterNo { get; set; }
        public Nullable<System.DateTime> UCDate { get; set; }
        public Nullable<double> UCAmount { get; set; }
    }
}
