//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Code_Slum
    {
        public long SlumId { get; set; }
        public string SlumName { get; set; }
        public Nullable<double> SlumCovered { get; set; }
        public string ProjectCode { get; set; }
    }
}
