//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnInv
    {
        public long SrNo { get; set; }
        public Nullable<decimal> Return1 { get; set; }
        public Nullable<decimal> Return2 { get; set; }
        public Nullable<decimal> Return3 { get; set; }
        public Nullable<decimal> Return4 { get; set; }
        public Nullable<decimal> Return5 { get; set; }
        public Nullable<decimal> Return6 { get; set; }
        public Nullable<decimal> Return7 { get; set; }
        public Nullable<decimal> Return8 { get; set; }
        public Nullable<decimal> Return9 { get; set; }
        public Nullable<decimal> Return10 { get; set; }
        public Nullable<decimal> UC1 { get; set; }
        public Nullable<decimal> UC2 { get; set; }
        public Nullable<decimal> UC3 { get; set; }
        public Nullable<decimal> UC4 { get; set; }
        public Nullable<decimal> UC5 { get; set; }
        public Nullable<decimal> UC6 { get; set; }
        public Nullable<decimal> UC7 { get; set; }
        public Nullable<decimal> UC8 { get; set; }
        public Nullable<decimal> UC9 { get; set; }
        public Nullable<decimal> UC10 { get; set; }
    }
}
