//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndicator
    {
        public long SrNo { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public string Indicator1 { get; set; }
        public string Indicator2 { get; set; }
        public string Indicator3 { get; set; }
        public string Indicator4 { get; set; }
        public string Indicator5 { get; set; }
        public string Indicator6 { get; set; }
        public string UserId { get; set; }
        public string Remarks { get; set; }
    }
}
