//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMAYU
    {
        public long SrNo { get; set; }
        public string FinYear { get; set; }
        public string HouseInv { get; set; }
        public string FundsDisp { get; set; }
        public string IIndI { get; set; }
        public string III_I { get; set; }
        public string HG { get; set; }
        public string HC { get; set; }
        public string HO { get; set; }
    }
}
