//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhysicalCityYearWise
    {
        public long srno { get; set; }
        public string Fin_Year { get; set; }
        public string Grounded { get; set; }
        public string Sanctioned { get; set; }
        public string Completed { get; set; }
        public string Occupied { get; set; }
    }
}
