//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster_not_used
    {
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PIN { get; set; }
        public string FRN { get; set; }
        public string FAX { get; set; }
        public string PAN { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string CompanyId { get; set; }
        public string TAN { get; set; }
        public string Service_Tax_No { get; set; }
        public string Authorised_Person { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedFor { get; set; }
        public string RoleId { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Aadhar { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<decimal> PlanAmount { get; set; }
        public string PF_NO { get; set; }
        public string ESI_NO { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string PrevEmployerName { get; set; }
        public string PrevEmployerAddress { get; set; }
        public string PrevEmployerPeriodServed { get; set; }
        public string PrevEmployerContactDetails { get; set; }
        public string PermanentPhoneNo { get; set; }
        public string M_NO { get; set; }
        public string NRO_NO { get; set; }
        public string Leaves { get; set; }
        public Nullable<System.DateTime> ArticleshipCompletionDate { get; set; }
        public string FinalExaminationDue { get; set; }
        public string NextDue { get; set; }
        public string ExaminationCleared { get; set; }
        public string Remarks { get; set; }
        public string BusinessDescription { get; set; }
        public string Engagement { get; set; }
    }
}
