//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorMaster
    {
        public long SrNo { get; set; }
        public Nullable<long> VisitorId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> Dcode { get; set; }
        public Nullable<long> CityCode { get; set; }
        public string ProjectName { get; set; }
        public string Notes { get; set; }
        public string Description { get; set; }
        public string Extra { get; set; }
        public string Userid { get; set; }
        public Nullable<bool> sFlag { get; set; }
    }
}
