//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReportAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_FileUpload
    {
        public long UploadId { get; set; }
        public string NameofFile { get; set; }
        public string Path { get; set; }
        public string TypeOfFile { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<long> VisitorId { get; set; }
    }
}
